export default {
	GET_CURRENT_LOCATION : "GET_CURRENT_LOCATION",
	GET_USER_INPUT : "GET_USER_INPUT",
	GET_ADDRESS_PREDICTION : "GET_ADDRESS_PREDICTION",
	INPUT_TYPE :"INPUT_TYPE",
	GET_SELECTED_ADDRESS : "GET_SELECTED_ADDRESS"
} 